replicaCount: 1

image:
  repository: tecknosap/globalsend   # full Docker Hub repo
  tag: latest
  pullPolicy: IfNotPresent            # or Always, safer for remote image

service:
  type: ClusterIP
  port: 80