apiVersion: apps/v1
kind: Deployment
metadata:
  name:  globalsend  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: globalsend   
  template:
    metadata:
      labels:
        app: globalsend
    spec:
      containers:
        - name: globalsend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80